# Generated by Django 4.0 on 2022-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
